- hosts: ansiblehost
  become: yes
  vars_files:
    - group_vars/all/common_vars.yml
  roles:
    - 1-create-powerdns-and-PNE-role
    - 2-configure-powerdns-role
    - 3-docker-prometheus-grafana-config
