- name: copy .sh config file to remote host
  copy:
    src: files/setup.sh
    dest: /tmp
    mode: '0755'

- name: run .sh file to create zone and records into powerdns
  command:
    - chmod +x /tmp/setup.sh
    - /tmp/setup.sh
