- name: copy .sh config file to remote host
  copy:
    src: files/setup.sh
    dest: /tmp
    mode: a+x
    owner: root
    group: root

- name: run .sh file to create zone and records into powerdns
  command: /tmp/setup.sh >> /tmp/outcomesetup.txt
