- name: install yum-utils
  yum:
    name: yum-utils
    state: latest

- name: install docker repo
  shell: yum-config-manager --add-repo {{ docker_repo }}

- name: enable nightly
  shell: yum-config-manager --enable docker-ce-nightly

- name: enable test
  shell: yum-config-manager --enable docker-ce-test

- name: install docker
  yum:
    name: docker-ce
    state: latest
  notify:
    - restart docker
    - enable on boot


