- name: update yum
  command: yum update -y

- name: install yum-utils
  yum:
    name:
     - yum-utils
     - device-mapper-persistent-data
     - lvm2
    state: latest

- name: install docker repo
  shell: yum-config-manager --add-repo {{ docker_repo }}

- name: enable nightly
  shell: yum-config-manager --enable docker-ce-nightly

- name: enable test
  shell: yum-config-manager --enable docker-ce-test

- name: install docker
  yum:
    name:
     - docker-ce
     - docker-ce-cli
     - containerd.io
    state: latest

  notify:
    - restart docker
    - enable on boot

- name: restart docker
  systemd:
    name: docker
    state: restarted

