- name: adding prometheus user group
  group:
    name: prometheus
    state: present
    system: true

- name: adding prometheus user
  user:
    name: prometheus
    groups: prometheus
    append: true
    shell: /bin/bash

- name: getting node exporter
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: /tmp

- name: extract node exporter to home dir (no need to creat additional folders)
  unarchive:
    src: /tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz
    dest: "{{ node_exporter_working_path }}/"
    owner: prometheus
    group: prometheus
    remote_src: yes

- name: move extracted files to node_exported folder
  copy:
    src: "{{ node_exporter_working_path }}/node_exporter-{{ node_exporter_version }}.linux-amd64/"
    dest: "{{ node_exporter_working_path }}/node_exporter"
    owner: prometheus
    group: prometheus
    mode: 0755
    remote_src: yes

- name: change file permissions
  file:
    path: "{{ node_exporter_working_path }}/node_exporter/node_exporter"
    owner: prometheus
    group: prometheus
    mode: 0755

- name: copy config file to systemd
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart systemd
    - restart node_exporter
    - enable on boot







