- name: install EPEL repository to get pdns server
  yum:
    name: "{{ epel_repo }}"
    state: latest

- name: Install latest version of PowerDNS
  yum:
    name: pdns
    state: latest

- name: expose API, setting DB path
  blockinfile:
    path: "{{ pdns_config_file }}"
    block: |
      api=yes
      api-key={{ pdns_api_key }}
      webserver=yes
      webserver-port={{ pdns_webserver_port }}
      gsqlite3-database={{ sqlite3_db_path }}

- name: Install and configure sqlite as a backend
  yum:
    name:
     - pdns-backend-sqlite
     - sqlite
    state: latest

- name: setting the default backend as sqlite3
  ansible.builtin.lineinfile:
      path: "{{ pdns_config_file }}"
      regexp: '^launch='
      line: 'launch={{ pdns_backend }}'

- name: cretaing DB path
  ansible.builtin.file:
    dest: "{{ pdns_db_path }}"
    state: directory
    recurse: yes
    owner: pdns
    group: pdns
    mode: '0755'

- name: creating the database and restarting powerdns
  shell: sqlite3 {{ sqlite3_db_path }} < /usr/share/doc/pdns/schema.sqlite3.sql
  ignore_errors: yes
  notify: restart powerdns



