---
# handlers file for 1-create-powerdns-and-PNE-role

- name: restart powerdns
  service:
    name: pdns
    state: restarted

- name: restart systemd
  systemd:
    name: systemd
    daemon_reload: true

- name: restart node_exporter
  systemd:
    name: node_exporter
    state: restarted

- name: enable on boot
  service:
    name: node_exporter
    state: started
    enabled: true